replicaCount: 1

service:
  type: ClusterIP
  port: 8080

resources: {}

# Application configuration surfaced via ConfigMap
config:
  spring:
    application:
      name: front-ui
  shared:
    gatewayBaseUrl: "http://{{ .Release.Name }}.192.168.49.2.nip.io"
  security:
    oauth2:
      provider:
        keycloak:
          issuerUri: "http://{{ .Release.Name }}.192.168.49.2.nip.io/keycloak/realms/master"
      registration:
        front_ui_client:
          clientId: "front_ui_client"
          clientSecret: "EMgj3OIlpjhemWPhujno1hn1q1AC1AbT"

  debug:
    port: 5005        # локально будем форвардить на этот порт
    suspend: "n"      # "y" — JVM ждёт подключение перед стартом
