version: '3.8'

services:

#  consul:
#    image: consul:1.15
#    container_name: consul
#    ports:
#      - "8500:8500"
#      - "8600:8600/udp"
#    command: agent -server -bootstrap -ui -client=0.0.0.0
#    volumes:
#      - consul_data:/consul/data
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  postgres:
    image: postgres:13
    container_name: spring_postgres
    environment:
      POSTGRES_DB: bankapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

#  keycloak:
#    image: quay.io/keycloak/keycloak:26.1.3
#    container_name: keycloak
#    environment:
#      KC_BOOTSTRAP_ADMIN_USERNAME: admin
#      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
#      KC_HTTP_PORT: 8100  # Меняем внутренний порт
#    ports:
#      - "8100:8100"
#    command: start-dev
#    depends_on:
#      - postgres
#    restart: unless-stopped
#
#  accounts:
#    build:
#      context: ./accounts
#    container_name: accounts
#    ports:
#      - "8010:8010"
#    depends_on:
#      - postgres
#    restart: unless-stopped
#
#  front-ui:
#    build:
#      context: ./front-ui
#    container_name: front-ui
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    restart: unless-stopped
#
volumes:
  postgres_data:
  consul_data:
