apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  application.yml: |-
    server:
      port: {{ .Values.service.port }}

    management:
      endpoints:
        web:
          exposure:
            include: health,info,env,refresh

    logging:
      level:
        org.springframework.web: INFO

    spring:
      datasource:
        url: jdbc:postgresql://{{ .Release.Name }}-postgres:{{ .Values.database.port }}/{{ .Values.database.name }}
        username: {{ .Values.database.username | quote }}
        password: {{ .Values.database.password | quote }}

    keycloak:
      url: http://{{ .Release.Name }}-keycloak:{{ .Values.keycloak.port }}{{ .Values.keycloak.relativePath }}

    blocker:
      url: http://{{ .Release.Name }}-blocker:{{ .Values.blocker.port }}/blocker

    shared:
      gateway-base-url: http://bankapp.{{ .Values.global.minikubeIp }}.nip.io
