server:
  port: 8070

spring:
  application:
    name: transfer
  config:
    import: "consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: transfer
        health-check-path: /actuator/health
        health-check-interval: 10s
  datasource:
    url: jdbc:postgresql://localhost:5431/bankapp
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.web: INFO

app:
  # Меняй на 'http://gateway' если дергаешь через docker network
  gateway-base-url: http://localhost:8080
