spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/bankapp
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  config:
    import: "consul:"
  application:
    name: transfer            # Логическое имя сервиса A
  cloud:
    consul:
      host: localhost          # Адрес Consul (по умолчанию localhost)
      port: 8500               # Порт Consul (8500 по умолчанию)
      discovery:
        service-name: transfer  # Необязательно, по умолчанию берётся spring.application.name
        health-check-path: /actuator/health   # Путь к health-check
        health-check-interval: 10s            # Интервал проверки
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        prefix: config           # Префикс в KV-хранилище Consul (по умолчанию "config")
        defaultContext: application  # Контекст по умолчанию
server:
  port: 8070                   # Порт сервиса А (например, 8080)
management:
  endpoints:
    web:
      exposure:
        include: beans,health,info
  endpoint:
    beans:
      enabled: true
    health:
      enabled: true
