enabled: true

replicaCount: 1

image:
  repository: opensearchproject/logstash-oss-with-opensearch-output-plugin
  tag: "7.16.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9600

resources: {}

persistence:
  enabled: false

kafka:
  bootstrapServers: "kafka:9092"
  topics:
    - bankapp-logs
  groupId: "logstash-bankapp"
  clientId: "logstash-bankapp"
  consumerThreads: 1
  autoOffsetReset: "earliest"

# Лёгкие лимиты JVM
javaOpts: "-Xms256m -Xmx256m"

# Ничего не мониторим — минимум
prometheus:
  serviceMonitor:
    enabled: false

opensearch:
  host: opensearch-cluster-master         # если пусто — будет <release>-opensearch
  port: 9200
  indexPrefix: "bankapp-logs"
