apiVersion: v2
name: bankapp-chart
description: Umbrella chart for BankApp
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kafka
    version: '>=32.0.0'
    repository: "file://charts/kafka"
    alias: kafka
    condition: kafka.enabled
  - name: prometheus
    version: 27.*
    repository: "file://charts/prometheus"
    condition: prometheus.enabled
  - name: grafana
    version: "8.*"
    repository: "file://charts/grafana"
    condition: grafana.enabled
  - name: opensearch
    repository: "file://charts/opensearch"
    version: 2.22.0
    condition: opensearch.enabled
  - name: opensearch-dashboards
    repository: https://opensearch-project.github.io/helm-charts/
    version: 2.22.0
    condition: opensearch-dashboards.enabled
