grafana:
  enabled: true

  adminUser: admin
  adminPassword: admin

  service:
    type: ClusterIP
    port: 3000

  ingress:
    enabled: false

  persistence:
    enabled: false

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://bankapp-prometheus-server
          isDefault: true
          jsonData:
            httpMethod: POST

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    default: {}
