prometheus:
  enabled: true

  server:
    persistentVolume:
      enabled: false   # удобно для minikube/отладки

    global:
      scrape_interval: 30s
      evaluation_interval: 30s
      scrape_timeout: 10s

    retention: 2d
