global:
  minikubeIp: "192.168.49.2"
  imagePrefix: "ghcr.io/evggene"
  pullPolicy: IfNotPresent
  tag: "0.0.3-SNAPSHOT"

ingress:
  enabled: true
  className: "nginx"

keycloak:
  service:
    port: 8101
accounts:
  service:
    port: 8010
front-ui:
  service:
    port: 8060
cash:
  service:
    port: 8030
exchange:
  service:
    port: 8040
transfer:
  service:
    port: 8090
notifications:
  service:
    port: 8070
blocker:
  service:
    port: 8020
exchange-generator:
  service:
    port: 8050
kafka:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/kafka
    tag: 4.0.0-debian-12-r10

  metrics:
    jmx:
      # enabled: true
      image:
        registry: docker.io
        repository: bitnami/jmx-exporter
        tag: 1.4.0-debian-12-r0

  fullnameOverride: kafka
  kraft:
    enabled: true
  controller:
    replicaCount: 1
  broker:
    replicaCount: 1
  listeners:
    client:
      protocol: PLAINTEXT

  provisioning:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/os-shell
    kubectl:
      image:
        registry: docker.io
        repository: bitnami/kubectl
    topics:
      - name: notifications.events
        partitions: 3
        replicationFactor: 1
      - name: exchange.rates
        partitions: 3
        replicationFactor: 1
      - name: cash.operations
        partitions: 3
        replicationFactor: 1
      - name: transfer.operations
        partitions: 3
        replicationFactor: 1
