postgres:
  image: "postgres:12.5"
  imagePullPolicy: IfNotPresent
  service:
    port: 5432
  credentials:
    database: bankapp
    username: user
    password: pass
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: ""
  resources: {}

keycloak:
  image: "quay.io/keycloak/keycloak:26.1.3"
  imagePullPolicy: IfNotPresent
  replicas: 1

  admin:
    username: admin
    password: admin

  db:
    host: ""
    port: 5432
    name: bankapp
    username: user
    password: pass

  service:
    port: 8080
    type: ClusterIP

  ingress:
    enabled: true
    className: "nginx"
    host: ""
    path: /
    tls:
      enabled: false
      secretName: ""

  proxy: edge
  hostname: ""
