global:
  minikubeIp: "192.168.49.2"
  imageRegistry: "ghcr.io/evggene"
  pullPolicy: IfNotPresent
  tag: "0.0.1"

ingress:
  enabled: true
  className: "nginx"

keycloak:
  service:
    port: 8101

accounts:
  service:
    port: 8010

front-ui:
  service:
    port: 8060

cash:
  service:
    port: 8030

exchange:
  service:
    port: 8040

transfer:
  service:
    port: 8090

notifications:
  service:
    port: 8070

blocker:
  service:
    port: 8020

exchange-generator:
  service:
    port: 8050
