global:
  minikubeIp: "192.168.49.2"
ingress:
  enabled: true
  className: "nginx"
accounts:
  service:
    port: 8010

keycloak:
  service:
    port: 8101

front-ui:
  service:
    port: 8060

exchange-generator:
  service:
    port: 8050

blocker:
  service:
    port: 8040
