global:
  minikubeIp: "192.168.49.2"
  imageRegistry: "ghcr.io/evggene"
  pullPolicy: IfNotPresent
  tag: "0.0.1"

ingress:
  enabled: true
  className: "nginx"

keycloak:
  service:
    port: 8101
accounts:
  service:
    port: 8010
front-ui:
  service:
    port: 8060
cash:
  service:
    port: 8030
exchange:
  service:
    port: 8040
transfer:
  service:
    port: 8090
notifications:
  service:
    port: 8070
blocker:
  service:
    port: 8020
exchange-generator:
  service:
    port: 8050
kafka:
  enabled: true
  # Основной контейнер Kafka
  image:
    registry: docker.io
    repository: bitnami/kafka
    tag: 4.0.0-debian-12-r10
  # (Опционально) JMX-экспортер
  metrics:
    jmx:
      # enabled: true        # включите при необходимости
      image:
        registry: docker.io
        repository: bitnami/jmx-exporter
        tag: 1.4.0-debian-12-r0
  fullnameOverride: kafka
  kraft:
    enabled: true
  controller:
    replicaCount: 1
  broker:
    replicaCount: 1
  listeners:
    client:
      protocol: PLAINTEXT
  # Provisioning (темы + образы os-shell/kubectl явно из docker.io/bitnami)
  provisioning:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/os-shell
      # tag: 12-debian-12-r51  # можно зафиксировать при желании
    kubectl:
      image:
        registry: docker.io
        repository: bitnami/kubectl
        tag: 1.33.4-debian-12-r0
    topics:
      - name: notifications.events
        partitions: 3
        replicationFactor: 1
      - name: exchange.rates
        partitions: 3
        replicationFactor: 1
      - name: cash.operations
        partitions: 3
        replicationFactor: 1
      - name: transfer.operations
        partitions: 3
        replicationFactor: 1
