replicaCount: 1
image:
  repository: openzipkin/zipkin
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9411

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
