spring:
  cloud:
    consul:
      config:
        enabled: false
  application:
    name: accounts
  datasource:
    url: jdbc:postgresql://localhost:5431/bankapp
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://keycloak:8101/realms/myrealm

server:
  port: 8010

resilience4j:
  retry:
    instances:
      accountsToBlocker:
        max-attempts: 5
        wait-duration: 300ms

  circuitbreaker:
    instances:
      accountsToBlocker:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20
        failure-rate-threshold: 40
        wait-duration-in-open-state: 5s

  timelimiter:
    instances:
      default:
        timeout-duration: 2s

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,refresh
logging:
  level:
    org.springframework.web: INFO

keycloak:
  url: http://localhost:8101
