image: "postgres:12.5"
imagePullPolicy: IfNotPresent
service:
  port: 5432
credentials:
  database: bankapp
  username: user
  password: pass
persistence:
  enabled: true
  size: 1Gi
  storageClassName: ""
resources: {}
