server:
  port: 8080
spring:
  application:
    name: front-ui
  cloud:
    gateway:
      mvc:
        routes:
          - id: some-service-route  # ID роута
            uri: http://127.0.0.1:9001  # URI целевого микросервиса
            predicates:
              - Path=/some-service/**   # URI поступающего в Gateway запроса
            filters:
              - RewritePath=/some-service/?(?<segment>.*), /$\{segment}
