apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  application.yml: |
    spring:
      application:
        name: accounts
      datasource:
        url: jdbc:postgresql://{{ .Release.Name }}-postgres:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}
        username: {{ .Values.postgres.username }}
        password: {{ .Values.postgres.password }}
      jpa:
        hibernate:
          ddl-auto: none
        show-sql: true
        properties:
          hibernate:
            format_sql: true
      security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: http://{{ .Release.Name }}-keycloak:{{ .Values.keycloak.port }}/realms/{{ .Values.keycloak.realm }}/protocol/openid-connect/certs

    server:
      port: {{ .Values.service.port }}
    
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      tracing:
        sampling:
          probability: 1.0
        export:
          zipkin:
            enabled: true
            endpoint: http://{{ .Release.Name }}-zipkin:9411/api/v2/spans
    
    logging:
      pattern:
        level: "%5p [${spring.application.name:},traceId=%X{traceId},spanId=%X{spanId}]"
    
    keycloak:
      url: "http://{{ .Release.Name }}.192.168.49.2.nip.io/keycloak"
