apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accounts.fullname" . }}-config
  labels:
    {{- include "accounts.labels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      application:
        name: accounts
      datasource:
        url: jdbc:postgresql://{{ include "accounts.postgresHost" . }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}
        username: {{ .Values.postgres.username }}
        password: {{ .Values.postgres.password }}
      jpa:
        hibernate:
          ddl-auto: none
        show-sql: true
        properties:
          hibernate:
            format_sql: true
      security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: http://{{ include "accounts.keycloakHost" . }}:{{ .Values.keycloak.port }}/realms/{{ .Values.keycloak.realm }}/protocol/openid-connect/certs

    server:
      port: 8010

    management:
      endpoints:
        web:
          exposure:
            include: health,info
