apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "accounts.fullname" . }}
  labels:
    {{- include "accounts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "accounts.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "accounts.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: accounts
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8010
          volumeMounts:
            - name: app-config
              mountPath: /config
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
              ports:
                - containerPort: 8010
                - containerPort: 5005
            - name: SPRING_CLOUD_DISCOVERY_ENABLED
              value: "false"
            - name: SPRING_CLOUD_SERVICE-REGISTRY_AUTO-REGISTRATION_ENABLED
              value: "false"
            - name: SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED
              value: "false"
            - name: SPRING_CLOUD_CONSUL_CONFIG_ENABLED
              value: "false"
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:/config/"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8010
#            initialDelaySeconds: 10
#            periodSeconds: 10
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8010
#            initialDelaySeconds: 20
#            periodSeconds: 20
      volumes:
        - name: app-config
          configMap:
            name: {{ include "accounts.fullname" . }}-config
