apiVersion: v1
kind: Service
metadata:
  name: {{ include "accounts.fullname" . }}
  labels:
    {{- include "accounts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8010
  selector:
    app.kubernetes.io/name: {{ include "accounts.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
