apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logstash.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    pipeline.ordered: auto
    pipeline.workers: {{ .Values.kafka.consumerThreads | default 1 }}
    queue.type: memory
