apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-transfer
  labels:
    app.kubernetes.io/name: transfer
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: transfer
    app.kubernetes.io/instance: {{ .Release.Name }}
