apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-front-ui-config
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |
    server:
      servlet:
        session:
          cookie:
            name: FRONTUISESSION
            domain: bankapp.192.168.49.2.nip.io
            path: /
            same-site: Lax
            secure: false   # без TLS
    spring:
      application:
        name: {{ .Values.config.spring.application.name | default "front-ui" | quote }}
      security:
        oauth2:
          client:
            provider:
              keycloak:
                issuer-uri: "http://bankapp.192.168.49.2.nip.io/keycloak/realms/myrealm"
            registration:
              front_ui_client:
                client-id: front_ui_client
                client-secret: EMgj3OIlpjhemWPhujno1hn1q1AC1AbT
                scope: front_ui
                authorization-grant-type: client_credentials
    shared:
      gatewayBaseUrl: "http://bankapp.192.168.49.2.nip.io"
