apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-front-ui-config
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |
    spring:
      application:
        name: {{ .Values.config.spring.application.name | default "front-ui" | quote }}
      security:
        oauth2:
          client:
            provider:
              keycloak:
                issuer-uri: {{ default (printf "http://keycloak.%s.nip.io/realms/myrealm" .Values.global.minikubeIp) .Values.config.security.oauth2.provider.keycloak.issuerUri | quote }}
            registration:
              front_ui_client:
                client-id: {{ .Values.config.security.oauth2.registration.front_ui_client.clientId | quote }}
                client-secret: {{ .Values.config.security.oauth2.registration.front_ui_client.clientSecret | quote }}
    shared:
      gatewayBaseUrl: "http://bankapp.192.168.49.2.nip.io"
