apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  application.yml: |
    server:
      servlet:
        session:
          cookie:
            name: FRONTUISESSION
            domain: {{ .Release.Name }}.192.168.49.2.nip.io
            path: /
            same-site: Lax
            secure: false   # без TLS
      port: {{ .Values.service.port }}
    spring:
      application:
        name: {{ .Values.config.spring.application.name | default "front-ui" | quote }}
      security:
        oauth2:
          client:
            provider:
              keycloak:
                issuer-uri: "http://{{ .Release.Name }}.192.168.49.2.nip.io/keycloak/realms/master"
            registration:
              front_ui_client:
                client-id: front_ui_client
                client-secret: ZMXhPlTCqsQtqUf8nDh7VeCio6XGzj4U
                scope: front_ui
                authorization-grant-type: client_credentials
      kafka:
        bootstrap-servers: "http://kafka:9092"
        consumer:
          group-id: notifications
          auto-offset-reset: earliest
          enable-auto-commit: false
        listener:
          ack-mode: MANUAL_IMMEDIATE
    topics:
      exchange:
        topic: exchange.rates
    shared:
      gatewayBaseUrl: "http://{{ .Release.Name }}.192.168.49.2.nip.io"
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      tracing:
        sampling:
          probability: 1.0
      zipkin:
        tracing:
          endpoint: http://{{ .Release.Name }}-zipkin:9411/api/v2/spans
