apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  application.yml: |
    server:
      servlet:
        session:
          cookie:
            name: FRONTUISESSION
            domain: {{ .Release.Name }}.192.168.49.2.nip.io
            path: /
            same-site: Lax
            secure: false   # без TLS
      port: {{ .Values.service.port }}
    spring:
      application:
        name: {{ .Values.config.spring.application.name | default "front-ui" | quote }}
      security:
        oauth2:
          client:
            provider:
              keycloak:
                issuer-uri: "http://{{ .Release.Name }}.192.168.49.2.nip.io/keycloak/realms/myrealm"
            registration:
              front_ui_client:
                client-id: front_ui_client
                client-secret: eq9i8vJPf33zfDNsnVfKTlGV6eylWWqO
                scope: front_ui
                authorization-grant-type: client_credentials
    shared:
      gatewayBaseUrl: "http://{{ .Release.Name }}.192.168.49.2.nip.io"
