pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = credentials('DOCKER_REGISTRY')
        DB_PASSWORD     = credentials('DB_PASSWORD')
        GITHUB_USERNAME = credentials('GITHUB_USERNAME')
        DB_NAME         = 'mydb'
        DB_USER         = 'myuser'
        IMAGE_TAG       = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Build & Unit Tests') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Build Docker Images') {
            steps {
                sh """
                docker build -t ghcr.io/evggene/accounts:${IMAGE_TAG} accounts
                docker build -t ghcr.io/evggene/blocker:${IMAGE_TAG} blocker
                docker build -t ghcr.io/evggene/cash:${IMAGE_TAG} cash
                docker build -t ghcr.io/evggene/exchange:${IMAGE_TAG} exchange
                docker build -t ghcr.io/evggene/exchange-generator:${IMAGE_TAG} exchange-generator
                docker build -t ghcr.io/evggene/front-ui:${IMAGE_TAG} front-ui
                docker build -t ghcr.io/evggene/notifications:${IMAGE_TAG} notifications
                docker build -t ghcr.io/evggene/transfer:${IMAGE_TAG} transfer
                """
            }
        }

        stage('Push Docker Images') {
            steps {
                withCredentials([string(credentialsId: 'GHCR_TOKEN', variable: 'GHCR_TOKEN')]) {
                    sh """
                    echo \$GHCR_TOKEN | docker login ghcr.io -u ${GITHUB_USERNAME} --password-stdin
                    docker push  ghcr.io/evggene/accounts:${IMAGE_TAG}
                    docker push  ghcr.io/evggene/blocker:${IMAGE_TAG}
                    docker push  ghcr.io/evggene/cash:${IMAGE_TAG}
                    docker push  ghcr.io/evggene/exchange:${IMAGE_TAG}
                    docker push  ghcr.io/evggene/exchange-generator:${IMAGE_TAG}
                    docker push  ghcr.io/evggene/front-ui:${IMAGE_TAG}
                    docker push  ghcr.io/evggene/notifications:${IMAGE_TAG}
                    docker push  ghcr.io/evggene/transfer:${IMAGE_TAG}
                    """
                }
            }
        }

        stage('Helm Deploy to TEST') {
            steps {
                sh """
                helm upgrade --install bankapp bankapp-chart \\
                  --namespace test --create-namespace \\
                  --set image.tag=${IMAGE_TAG}
                """
            }
        }
    }
}
