apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-secret
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: {{ .Values.admin.username | quote }}
  KC_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.admin.password | quote }}
  KC_DB_USERNAME: {{ .Values.db.username | quote }}
  KC_DB_PASSWORD: {{ .Values.db.password | quote }}
