image:
  repository: accounts
  tag: "0.0.1-SNAPSHOT"
  pullPolicy: Never

replicaCount: 1

service:
  type: ClusterIP
  port: 8010

resources: {}

postgres:
  database: bankapp
  username: user
  password: pass
  port: 5432

keycloak:
  realm: myrealm
  port: 8101
