apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-osd-config
  namespace: {{ .Release.Namespace }}
data:
  opensearch_dashboards.yml: |
    server.host: "0.0.0.0"
    server.basePath: "/dashboards"
    server.rewriteBasePath: true
    opensearch.hosts: ["http://opensearch-cluster-master:9200"]
    opensearch.ssl.verificationMode: "none"
