spring:
  application:
    name: notifications

  config:
    import: "consul:"

spring.cloud.consul:
  host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
  port: ${SPRING_CLOUD_CONSUL_PORT:8500}
  discovery:
    enabled: true
    register: true
    service-name: ${spring.application.name}
    prefer-ip-address: true
  config:
    enabled: true
    prefix: config
    defaultContext: application
    format: YAML
    data-key: data
