apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  application.properties: |
    spring.application.name=notifications
    spring.kafka.bootstrap-servers=http://kafka:9092
    spring.kafka.consumer.group-id=notifications
    spring.kafka.consumer.auto-offset-reset=earliest
    spring.kafka.consumer.enable-auto-commit=true
    server.port={{ .Values.service.port }}
    logging.level.org.springframework.web=INFO
    management.endpoints.web.exposure.include=health,info
    topics.notifications.cash-topic=exchange.rates
